### ISSUE TITLE
wrapPeripheral not working correctly

### ISSUE THREAD

**Issue by Nathan1852** [RSDuck/RandomPeripherals#6]
Thanks for updating this so quickly.

Sadly I already have some bugs to report: 

It seems like the wrapPeripheral function doesn't work completely. 
I have the problems that I don't get the most return values (chest.getStackInSlot(1) for example) and that the peripheral wrapped with wrapPeripheral dosn't actually update(?) for example monitor.write("Test") doesn't actually write anything.
It almost seems like the java functions behind those Lua functions don't get executed?
The Lua functions just return nothing

The function suckStack returns false even though it succesfully sucked the Item into the inventory.

The help function for the setBlock function of the hologram says that one should use 1-8 for the coorinates, The function errors though if one uses 8, since it only accepts 0-7

If one (accidently) destroys the hologram in creative it crashes with this error:

```
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at me.kemal.randomp.te.TileHologramProjector.onBlockClick(TileHologramProjector.java:357)
	at me.kemal.randomp.RandomPeripherals.playerInteract(RandomPeripherals.java:206)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1503_RandomPeripherals_playerInteract_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:140)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

**Comment by RSDuck** [comment]
Since she last Commit every Dug here listed was fixed

I will release the update probably tommorow

**Comment by Nathan1852** [comment]
Thank you for the fast fix
